# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 10:47
from __future__ import unicode_literals

import autoslug.fields
import base.util
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', sep='.', unique=True)),
            ],
            options={
                'ordering': ('order',),
                'permissions': (('view_category', 'Can view category'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', sep='.', unique=True)),
                ('description_html', models.TextField(max_length=2000, unique=True, verbose_name='Description in HTML')),
                ('description', models.TextField(max_length=1000, unique=True, verbose_name='Description in BBCode')),
            ],
            options={
                'ordering': ('order',),
                'permissions': (('view_forum', 'Can view forum'), ('create_forum_topic', 'Can create topics in forum'), ('delete_forum_topic', 'delete_topic'), ('edit_forum_topic', 'edit_topic'), ('delete_own_forum_topic', 'delete_own_topic'), ('edit_own_forum_topic', 'edit_own_topic'), ('moderate_forum', 'Moderate Forum (Moving topics between forums)'), ('moderate_forum_topic', 'Moderate Topics In Forum'), ('moderate_own_forum_topic', 'Moderate own topics in forum'), ('moderate_own_forum_topic_posts', 'Moderate own posts in topics in forum')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('message_html', models.TextField(db_index=True, max_length=50000, verbose_name='Message in HTML')),
                ('message', models.TextField(db_index=True, max_length=40000, verbose_name='Message in BBCode')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='topic__slug', sep='.')),
                ('_message_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=base.util.message_metadata_factory)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical post',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
                ('forum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('message_html', models.TextField(max_length=50000, unique=True, verbose_name='Message in HTML')),
                ('message', models.TextField(max_length=40000, unique=True, verbose_name='Message in BBCode')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='topic__slug', sep='.', unique=True)),
                ('_message_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=base.util.message_metadata_factory)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts_from', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', sep='.', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics_from', to=settings.AUTH_USER_MODEL, verbose_name='From')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Forum')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Topic', verbose_name='In Topic'),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='topic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='forum',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Owner'),
        ),
    ]
