# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forum_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
