# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170726_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='forum_icons'),
        ),
    ]
