# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 19:59
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='pk', sep='.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='pk', sep='.', unique=True),
        ),
    ]
