# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 04:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170826_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('order',), 'permissions': (('view_forum', 'Can view forum'), ('create_forum_topic', 'Can create topics in forum'), ('delete_forum_topic', 'delete_topic'), ('edit_forum_topic', 'edit_topic'), ('delete_own_forum_topic', 'delete_own_topic'), ('edit_own_forum_topic', 'edit_own_topic'), ('moderate_forum', 'Moderate Forum (Moving topics between forums)'), ('moderate_forum_topic', 'Moderate Topics In Forum'), ('moderate_own_forum_topic', 'Moderate own topics in forum'), ('moderate_own_forum_topic_posts', 'Moderate own posts in topics in forum'), ('view_votes_topic', 'Can view exact number of votes for topic'), ('view_votes_topic_posts', 'Can view exact number of votes for topic posts'), ('up_vote_topic', 'Can upvote topics'), ('down_vote_topic', 'Can downvote topics'), ('up_vote_topic_post', 'Can upvote posts'), ('down_vote_topic_post', 'Can downvote posts'), ('view_topic_as_mode_tree', 'Can set tree view mode'), ('view_topic_as_mode_classic', 'Can set classic view mode'), ('view_topic_as_mode_tree_vote', 'Can set tree+vote view mode'), ('view_topic_as_mode_classic_vote', 'Can set classic+vote view mode'), ('sort_topic_by_hot', 'Can sort by hot'), ('sort_topic_by_recent', 'Can sort by recent'), ('sort_topic_by_votes', 'Can sort by votes'), ('sort_topic_by_old', 'Can sort by old'))},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('view_content', 'Can view topic content'),)},
        ),
        migrations.AddField(
            model_name='forum',
            name='default_sort_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'user'), (1, 'hot'), (2, 'creation'), (3, 'reply'), (4, 'votes'), (5, 'old')], default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='default_topic_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'user'), (1, 'classic'), (2, 'tree'), (3, 'classic+votes'), (4, 'tree+votes')], default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='enabled_sort_modes',
            field=forum.models.ChoiceArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'user'), (1, 'hot'), (2, 'creation'), (3, 'reply'), (4, 'votes'), (5, 'old')], default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='forum',
            name='enabled_topic_modes',
            field=forum.models.ChoiceArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'user'), (1, 'classic'), (2, 'tree'), (3, 'classic+votes'), (4, 'tree+votes')], default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='forum',
            name='enabled_voting',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='default_mode_override',
            field=models.PositiveSmallIntegerField(choices=[(0, 'forum default'), (1, 'classic'), (2, 'tree'), (3, 'classic+votes'), (4, 'tree+votes')], default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='forum_icons'),
        ),
        migrations.AddField(
            model_name='topic',
            name='stickied',
            field=models.BooleanField(default=False),
        ),
    ]
