# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20180212_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='enabled_sort_modes',
            field=forum.models.ChoiceArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'user'), (1, 'hot'), (2, 'creation'), (3, 'reply'), (4, 'votes'), (5, 'old')]), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='forum',
            name='enabled_topic_modes',
            field=forum.models.ChoiceArrayField(base_field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'user'), (1, 'classic'), (2, 'tree'), (3, 'classic+votes'), (4, 'tree+votes')]), default=list, size=None),
        ),
    ]
