# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 14:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steamauthprovider', '0003_auto_20170430_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPunishment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invokation time')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(max_length=4000)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('kind', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'AllBan'), (1, 'GameServerBan'), (2, 'TeamBan'), (4, 'TeamSpeakBan'), (5, 'SiteBan')]), size=None)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Revoked'), (0, 'Deleted')])),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='steamauthprovider.SteamUser')),
            ],
            options={
                'verbose_name': 'historical punishment',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invokation time')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(max_length=4000)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('kind', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'AllBan'), (1, 'GameServerBan'), (2, 'TeamBan'), (4, 'TeamSpeakBan'), (5, 'SiteBan')]), size=None)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Revoked'), (0, 'Deleted')])),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_punishments', to=settings.AUTH_USER_MODEL, verbose_name='Invoker')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='steamauthprovider.SteamUser')),
            ],
            options={
                'ordering': ('invoked_at', 'status', 'kind'),
                'permissions': (('invoke_punishment', 'Invoke'), ('revoke_punishment', 'Revoke'), ('soft_delete_punishment', 'Delete'), ('change_kind_punishment', 'Change Kind')),
            },
        ),
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
