# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:16
from __future__ import unicode_literals

import base.util
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('message_html', models.TextField(max_length=50000, unique=True, verbose_name='Message in HTML')),
                ('message', models.TextField(max_length=40000, unique=True, verbose_name='Message in BBCode')),
                ('_message_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=base.util.message_metadata_factory)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_from', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenericPostsByViewAndPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_object_name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenericPostsViewsThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.GenericPost')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.GenericPostsByViewAndPos')),
            ],
            options={
                'ordering': ('view', 'order'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalGenericPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('message_html', models.TextField(db_index=True, max_length=50000, verbose_name='Message in HTML')),
                ('message', models.TextField(db_index=True, max_length=40000, verbose_name='Message in BBCode')),
                ('_message_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=base.util.message_metadata_factory)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical generic post',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='SideBarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.SideBarEntry')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='genericpostsbyviewandpos',
            unique_together=set([('view_object_name', 'position')]),
        ),
        migrations.AddField(
            model_name='genericpost',
            name='parent_views',
            field=models.ManyToManyField(through='base.GenericPostsViewsThroughModel', to='base.GenericPostsByViewAndPos'),
        ),
    ]
