# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170429_1319'),
    ]

    operations = [
    ]
