# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sidebarentry_faicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarentry',
            name='faicon',
        ),
    ]
