# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170504_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_posts_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
