# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamauthprovider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='preferred_name_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Steam Name'), (2, 'Self Defined Name')], default=1),
        ),
    ]
