# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamauthprovider', '0002_steamuser_preferred_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steamuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
