# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 01:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('for_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='usersettings.UserSetting')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettingValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('regex', 'Regex valid if match'), ('regex-inverse', 'Regex valid if no match'), ('exact', 'Allows this exact value'), ('max', 'Max number'), ('min', 'Min number'), ('max-len', 'Max lenght'), ('min-len', 'Min lenght'), ('any', 'Allow any value')], default='any', max_length=255)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('fail_message', models.CharField(blank=True, max_length=500, null=True)),
                ('hint_message', models.CharField(blank=True, max_length=500, null=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='usersetting',
            name='userconfig_validation',
            field=models.ManyToManyField(to='usersettings.UserSettingValidator'),
        ),
        migrations.AlterUniqueTogether(
            name='usersettingdata',
            unique_together=set([('for_setting', 'for_user')]),
        ),
    ]
