# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_gameserver_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='stats.Teams'),
        ),
    ]
