# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20170327_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='stats.Team'),
        ),
    ]
