# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170327_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.Game'),
        ),
    ]
