# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170327_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
