# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_gameserver_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlog',
            name='tags',
        ),
        migrations.AddField(
            model_name='serverlog',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.LogTag'),
        ),
    ]
