# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20170404_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlog',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.LogTag'),
        ),
    ]
