# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20170411_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='hostname',
        ),
    ]
